# Generated by Django 4.2.3 on 2023-07-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidademedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=40)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('preco', models.FloatField()),
                ('ncm', models.CharField(max_length=8)),
                ('saldoestoque', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.categoria')),
                ('unidademedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.unidademedida')),
            ],
        ),
    ]
