# Generated by Django 4.2.3 on 2023-07-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_produto_datacadastro_alter_categoria_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(max_length=40),
        ),
    ]
