# Generated by Django 4.2.3 on 2023-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_ativo_alter_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoquemax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoquemin',
            field=models.IntegerField(default=0),
        ),
    ]
